#!/bin/sh

# You need to use the following line to enable the githook
# chmod u+x .git/hooks/post-checkout
# echo "Post checkout Git hook";

branch=$(git symbolic-ref --short HEAD)

test="$(date) Checked out $branch"

file=gitcheckouthistory.txt
if [ -e "$file" ]; then
    echo "File found!"
    echo $test >> $file
else
    echo $test > $file
    echo "file not found"
fi